branches:
  except:
    - appveyor

os: linux
dist: trusty
sudo: required
services: docker
language: minimal
install: skip
script: "./dist/linux/travis-ci.sh"

addons:
  apt:
    packages:
      - docker-ce

deploy:
  - &deploy-docker
    provider: script
    skip_cleanup: true
    script: ./dist/linux/deploy2dockerhub.sh "$IMAGE" "$TRAVIS_COMMIT_MESSAGE"
    on:
      repo: 1138-4EB/ghdl
      branch: rtd2travis
  - &deploy-releases
    provider: releases
    skip_cleanup: true
    api_key:
      secure: VzowiHBE7Lc14p/QOFvYYLz65g1uvYvffv32F2AVlpt4hs0EAdqME2+BLPnDDI1D4Oou30VXs2p37doI0J2qyyiT5TbSFzErYz+7uREYEOBWR5IQsK/iQrSxKOZ2Ox558T1zcObnZhVjAbV1yxQhdqitSWBCpayuNl4Gvubc0S1+MXhh/psvLgJ/r2Nq5gCAaoqmxvHUoNotQWYF5hKzynXPvV0wniB2l2HKc/UMK7jIu+GRKwMWk1NXuBk5ocreoAVrSH/FHD87K8wUfUqgaGjYRaniKbl2etMw4kcfRC1J+WtcUzVeHtb2tnlHo1Qk1tE7Dt5LMWYp0RlpiLfHmu4attHn2jdKBwdetGiB+admq7D6K0bROVQw6l1kJNYNROXR9PhA6ZkYQvDY1iF+RmikUee8zpGEZE0Ux1RjlCBAOE+yJu3/TWJpO3KCFEYKELqmljOgpaAu/ogyowLwDtakjzK1nA34CmgN9xwgARuxbzQNPxMIlFBeH4QJ9qMj3Jo9jUOxKF4dtSF5Y2t8p4XZ4RDBAwMb4QB35BaWCd7u2UwCVbks3CR7mdFXT22ZjN+92kgFOsqhsK67cNCXuUhL3jDAQ5His4qqca2+A25BVDFG3qz673gZotIq4/MYcBZx7daNJN88dFH47Rx8SDtiu7mb/6Y7TMaf7zW/KEs=
    file: "ghdl-*.tgz"
    file_glob: true
    on:
      repo: 1138-4EB/ghdl
      all_branches: true
      tags: true

# For each linux build, a different job/instance (with the constraints
# above) is executed in parallel in stage 'test'.
env:
  matrix:
    - IMAGE=stretch+mcode
    - IMAGE=stretch+mcode+gpl
#    - IMAGE=buster+mcode
#    - IMAGE=buster+mcode+gpl
    - IMAGE=ubuntu14+mcode
    - IMAGE=ubuntu14+llvm-3.8
#    - IMAGE=ubuntu16+mcode
#    - IMAGE=ubuntu16+llvm-3.9
#    - IMAGE=ubuntu18+mcode
#    - IMAGE=ubuntu18+llvm-5.0
    - IMAGE=fedora26+mcode
#    - IMAGE=fedora26+llvm
  global:
    - secure: "MZHtYkWdYK+SeYzJvWD8I0tbkdHGjmWyNDn70a2RrNYFu363Zt51ZvksEtkjrS7kdje6l6VPfLjilX5UtywIM1Mg6nt/rsw4p62+bGhMyhfXiqS3eqEfH2sThjosy773X8iotm2sW0ax0oHX07ZLcuTbZ+TK2cMGarZ+LzNT8IiMaeaWu4W7aE5LRxSmVRwcACUOa3NiC7GY/qC7vU2C8QNdXSlU3fSp17K5eccrkkBuiEhRTsdr3ZIhjOjrYzqHKWC3a0uHn/fJsbepsVM6FGt+zAwo0VqdXXCE2ts8EOATvFgEaCGxUgfGd/yvNsAG7sjF3nweR9Z11dpMbBE+TjxlLCXQ31v1Oj7pH6vcgjCYV69cZiLbsDhxTJFQ08qbm3xK8dmTUXFy1scrMSd8D/Q3Uf0LjHkH5Q5dL8TOyqejs57fUTIBtBUpCTvvGOErdZQAOWJc93sC9RQB7BuCDR2yR7rPTJr4KUwspe1uScA/H9cQS2p42SeJ4+Yyjtwod3IQWjr6+/pdNPoImleOP0dXSDCXpAIsbv6TR9curS3geLJuTmu5UnLzbURDr7Whtop3lCPbiN0H9jThSuyIxWUI+6JDGDG89RXbCyZvGz97sIShYstWg0U0xLWmw9IDez2HtK5VKuTT/hE7gDicZ0erN6r1dlix3SpuCtH1MlA=" #U
    - secure: "kIA09oCHzoHMK4LsfwcaVaMuoAFpd1M+M8tW3b9Rvki/hEB3y46edlb88lWVM7RgkNoCaIPwAZD7Wf3Xiq9Y7wWmqRsWQNRaorC0xke5SuyMwCSQSNo9S5jAu9SM5uxENCH9yucJl/vm2juYitJCHyYYMb4x17fy3sHKULNJ+JBqnrgOuTBYM1JOIkJVO1P5LqEXmqTtr6KgQgiTMtlvnM7hxjapgoyM3J1376f+Kfky0hUoDD7LFLXu8yQCn5Fnar8wR3czK6Qknafmckt5yWJxGOZobMDfKwOdA0fpU+XiArNQ/1NM80fGXq4YOGK5ycVQkO2ACxDqHYfQRYLlIfrUGp75BoXWwN6O1GoOrFcF7ZIoSaLoK3hZdvzRFT7dpUQFlosn00Y7VzqbosQM5QS5TBBqO+DExnkb399OpXI7o0lrlr232kjAeYqEb6N1n3M9BpiNW9Je4plJa/RDKwYsnC8Qak4G08PVTe6V711W1UtqMPd6efWFYTNvRW9tjO3v1lFGaGJ99ABP0AYLIDYWV3zfgvp0UzQOKFdWJj7dMQxdLMQ/bIETKn8P7NFjOWic4pgtp3zekZCL27blhc0fyHm62HUiVLT+VGFOI/nyclzBIZStSVuxPj2LvmAIiMnUNmWwds1ZqIZ21eiNykkn+k52ddTRHXIh2fhvWfg=" #P

stages:
#  - create ghdl/build and ghdl/run images
#  - test
  - build and update gh-pages

jobs:
  include:
    # A single job is described in its own stage, to create and push ghdl/build and ghdl/run images.
    - stage: create ghdl/build and ghdl/run images
      env: IMAGE=""
      script: if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[ci images]"; then ./dist/linux/create.sh; fi;
      deploy:
        - <<: *deploy-docker
    # A single additional job is described in stage 'test' for the macos build.
    # The constraints above are used, except explicitly overriden.
    - stage: test
      os: osx
      language: c
      osx_image: xcode7.3
      install: true
      cache:
        directories:
          - gnat
      env: IMAGE=macosx+mcode
      deploy:
        - <<: *deploy-releases
    - stage: build and update gh-pages
      script: ./dist/linux/gh-pages.sh
      deploy:
        - provider: script
          skip_cleanup: true
          script: DEPLOY=true ./dist/linux/gh-pages.sh
          on:
            repo: 1138-4EB/ghdl
            all_branches: true
            branch: master
